version: "2.4"

volumes:
   freeradius_config:
      name: freeradius_config

services:
   freeradius:
      hostname: freeradius
      environment:
         - TZ=Europe/London
         - domain_name=$domain_name
         - tld_name=$tld_name
         - domain_computers_sid=$domain_computers_sid
         - vpn_users_sid=$vpn_users_sid
         - primarykdc_name=$primarykdc_name
         - secondarykdc_name=$secondarykdc_name
      ports:
         - 1812:1812/udp
         - 1812:1813/udp
      image: boredazfcuk/freeradius
      healthcheck:
         test: /usr/local/bin/healthcheck.sh
         start_period: 30s
      restart: always
      volumes:
         - freeradius_config:/config
