version: "3.8"

services:
   freeradius:
      hostname: freeradius
      environment:
         - TZ=Europe/London
         - domain_name=$domain_name
         - tld_name=$tld_name
         - domain_computers_sid=$domain_computers_sid
         - vpn_users_sid=$vpn_users_sid
         - primarykdc=$primarykdc
         - secondarykdc=$secondarykdc
      ports:
         - "1812:1812"
      image: boredazfcuk/freeradius
      healthcheck:
         test: /usr/local/bin/healthcheck.sh
         start_period: 30s
      restart: always
